######## SpringBoot configuration ###############
server:
  port: 9090  #服务启动端口port

######## MySQL configuration ###############
spring:
  datasource:
    driver-cLass-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vuespring?servenTimezone=GMT%2b8
    username: root
    password: root
    mvc:
      pathmatch:
        matching-strategy: ANT_PATH_MATCHER

######## Mybatis configuration ###############
mybatis:
  mapper-locations: classpath:mapper/*.xml  #扫描所有mybatis文件
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #打印mybatis查询语句


######## Mybatis-plus configuration ###############
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

######## swagger configuration ###############
springdoc:
  packages-to-scan: ##需要扫描的包,可以配置多个
    - com.my.springboot.controller
  paths-to-exclude:  ##配置不包含在swagger文档中的api
    - /api/test/**
    - /api/mockito/data
  swagger-ui:
    enabled: true  #开启/禁止swagger,prod可以设置为false
    path: /swagger-ui.html  #swagger页面
  api-docs:
    enabled: true #开启/禁止api-docs, prod可以设置为false
    path: /api-docs #api的json文档
  use-management-port: false